
include ../../configurate.mk

COMPILE_FILES = $(wildcard $(SRC_DIR)/*.cpp)
COMPILE_FILES += ../../$(SRC_DIR)/Graphic.cpp ../../$(SRC_DIR)/hardware/TFT_ST7735.cpp

SKETCH_HEX  = $(BUILD_DIR)/test_lcd.hex
SKETCH_MAP  = $(BUILD_DIR)/test_lcd.map
SKETCH_ELF  = $(BUILD_DIR)/test_lcd.elf
SKETCH_LIST = $(BUILD_DIR)/test_lcd.lst

include ../../targets.mk