
include ../../configurate.mk

COMPILE_FILES = $(wildcard $(SRC_DIR)/*.cpp)
COMPILE_FILES += ../../$(SRC_DIR)/Graphic.cpp ../../$(SRC_DIR)/hardware/TFT_ST7735.cpp  ../../$(SRC_DIR)/UI_Engine.cpp
COMPILE_FILES += ../../$(SRC_DIR)/Global_Variables.cpp

SKETCH_HEX  = $(BUILD_DIR)/test_menu_joystick.hex
SKETCH_MAP  = $(BUILD_DIR)/test_menu_joystick.map
SKETCH_ELF  = $(BUILD_DIR)/test_menu_joystick.elf
SKETCH_LIST = $(BUILD_DIR)/test_menu_joystick.lst

include ../../targets.mk