
include ../../configurate.mk

COMPILE_FILES = $(wildcard $(SRC_DIR)/*.cpp)
COMPILE_FILES += ../../$(SRC_DIR)/Graphic.cpp ../../$(SRC_DIR)/hardware/TFT_ST7735.cpp ../../$(SRC_DIR)/hardware/Hardware.cpp

SKETCH_HEX  = $(BUILD_DIR)/test_btn.hex
SKETCH_MAP  = $(BUILD_DIR)/test_btn.map
SKETCH_ELF  = $(BUILD_DIR)/test_btn.elf
SKETCH_LIST = $(BUILD_DIR)/test_btn.lst

include ../../targets.mk